# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=255)),
                ('author_last_name', models.CharField(max_length=255)),
                ('quote', models.CharField(max_length=1000)),
            ],
        ),
    ]
